---
abstract: 'IO::Async support for Ryu stream management'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '1.126'
  Test::Fatal: '0.010'
  Test::More: '0.98'
  Test::Refcount: '0.07'
  Variable::Disposition: '0.004'
  indirect: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ryu-Async
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Ryu::Async:
    file: lib/Ryu/Async.pm
    version: '0.020'
  Ryu::Async::Client:
    file: lib/Ryu/Async/Client.pm
    version: '0.020'
  Ryu::Async::Packet:
    file: lib/Ryu/Async/Packet.pm
    version: '0.020'
  Ryu::Async::Process:
    file: lib/Ryu/Async/Process.pm
    version: '0.020'
  Ryu::Async::Server:
    file: lib/Ryu/Async/Server.pm
    version: '0.020'
recommends:
  Heap: '0'
  IO::Async::SSL: '0.19'
  IO::AsyncX::Sendfile: '0.002'
  IO::AsyncX::System: '0.003'
requires:
  Future: '0.47'
  Future::AsyncAwait: '0'
  IO::Async: '0.77'
  IO::Socket::IP: '0.41'
  Log::Any: '1.708'
  Ryu: '2.006'
  Syntax::Keyword::Try: '0'
  URI::tcp: '0'
  URI::udp: '0'
  curry: '1.001'
  namespace::clean: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Ryu-Async/issues
  homepage: https://github.com/team-at-cpan/Ryu-Async
  repository: https://github.com/team-at-cpan/Ryu-Async.git
version: '0.020'
x_authority: cpan:TEAM
x_contributors:
  - 'Eyad Arnabeh <eyadof@gmail.com>'
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
